[build]
  command = "npm --prefix client ci && npm --prefix client run build"
  publish = "client/build"

[[redirects]]
  from = "/api/*"
  to = "/api-fallback.json"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
